### PR TITLE
Fixed 'ProcessBuilder not found'

### PR DESCRIPTION
**Pull request by JimmDiGrizli**
Fixed bug #142

### CODE REVIEW

**Comment by rmrhz** [comment]
Why not just run `composer require symfony/process` and save the effort of having a tightly coupled dependency in the package?

**Comment by JimmDiGrizli** [comment]
I have a project on symfony 4.0, like many. ProcessBuilder was removed in symfony/component 4.0.
See https://github.com/symfony/process/blob/master/CHANGELOG.md

**Comment by aphofstede** [comment]
@jygaulier Could this be merged?

**Comment by jygaulier** [comment]
As said in the S4 doc, the way is to use the new class "process". We should not copy/paste S3 code to make Zippy S4 compliant.
If you can make a pr, we will merge it asap, and we will make a new branch (version) for S4.

**Comment by aphofstede** [comment]
https://github.com/alchemy-fr/Zippy/pull/147

**Pull request closed without merging**
