### PR TITLE
Replaces deprecated ProcessBuilder with lightly wrapped Symfony 4 Process

### PR DESCRIPTION
**Pull request by aphofstede**
@jygaulier Here's an alternative approach. I made a ZippyProcess class (extends Process) so the terse `add()` syntax could be preserved. I started fixing the test mocks but realised I had no idea what I was doing. If you guys like the way this is headed maybe you or someone else could help fixing the test suite.

### CODE REVIEW

**Comment by aphofstede** [comment]
Locally the error I got stumped on was:

> 1) Alchemy\Zippy\Tests\Adapter\BSDTar\TarBz2BSDTarAdapterTest::testCreateNoFiles
> Alchemy\Zippy\Exception\RuntimeException: Unable to execute the following command  {output: }
> 
> /Users/alex/src/Zippy/src/Adapter/AbstractTarAdapter.php:157
> /Users/alex/src/Zippy/src/Adapter/AbstractTarAdapter.php:29
> /Users/alex/src/Zippy/src/Adapter/AbstractAdapter.php:58
> /Users/alex/src/Zippy/tests/Tests/Adapter/BSDTar/BSDTarAdapterWithOptionsTest.php:137
> 

Travis has another ^

**Comment by jygaulier** [comment]
ouch!
`
.EESEEEEEE......EESE.EEEE......EESE.EEEE.....EE.E.EEEE.....EE.E  63 / 259 ( 24%)
EEEEE.....EE.E.EEEE......EEEEEE.EE.ESEEEEEEE................... 126 / 259 ( 48%)
............................................................... 189 / 259 ( 72%)
............................................................... 252 / 259 ( 97%)
.......                                                         259 / 259 (100%)
`
Please fix the code (not the tests) and run phpunit locally ok before making a pr.
If there is no other solution that a bc break (should not !), that implies a new zippy major release, please explain why.
Changing the tests is ok only to comply with the bc change.
It seems the error is always the same "Call to undefined method Mock_ProcessBuilder", so the fix should be simple (?).

**Comment by aphofstede** [comment]
@jygaulier The tests are trying to mock the now-removed Symfony ProcessBuilder class, so I don't see how you expect to keep the tests the same. (other than how PR https://github.com/alchemy-fr/Zippy/pull/146  did it) 
Like I said, I've been running phpunit locally and need help fixing those mocks. See my last commit, I only attempted to fix one test, so the others will naturally all fail.

**Comment by aphofstede** [comment]
@jygaulier You are aware that the current master branch also fails the tests, right?

**Comment by jygaulier** [comment]
I took the time to read the tests (I never worked on zippy). You are right, they must be changed since they use a "no-more-existing" class.
Sadly I really don't have time now to work on it, but we (Alchemy) will have to do it at some point, since we are moving our app(s) to S4. But zippy is not yet on the planning.

I just checked or own usage of zippy today : "alchemy/zippy": "^0.3.0"... We must find time for a big cleanup/bump of versions.
We will put this on the "todo-list"
Meanwhile, I will try to keep an eye on the repo. If someone else has a clean fix for it I will merge it asap.

So the only solution I may suggest today is a temporary fix your own usage on your fork (disabling tests), just to make zippy "do the job".
In fact, the copy/paste you did propose first is may be the best (temporary) fix on this messy repo, to have a "green" master.

Please give us the end of the week so I can talk about that with new developers.

Thks for your work on zippy.
JY

**Comment by jygaulier** [comment]
Alchemy will port Zippy to S4, but it cannot be a "top priority". This is expected to be done during jan. 2019.

**Pull request closed without merging**
